apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: healthhub-api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  replicas: 1
  selector:
    matchLabels:
      app: healthhub-api
  template:
    metadata:
      labels:
        app: healthhub-api
    spec:
      containers:
      # Primary Application Container
      - name: healthhub-api
        ports:
          - containerPort: 8080
        image: 277887097296.dkr.ecr.us-east-1.amazonaws.com/healthhub-api:2a5a7988710dd2177515a3f0ca8915b5609e595b
        args: ["npm", "start"]
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path:  /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path:  /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10  

---

apiVersion: v1
kind: Service
metadata:
  name: healthhub-api 
  labels:
    app: healthhub-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: healthhub-api 

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: healthhub-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /healthhubapi(/|$)(.*)
        backend:
          serviceName: healthhub-api
          servicePort: 80
